# configs.yaml

# ---------------------------------------------------------
# denoisers 
# ---------------------------------------------------------
default_denoiser: &default_denoiser
  num_classes: 70
  class_embed_dim: 16
  time_embed_dim: 32
  d_model: 64
  num_heads: 4
  num_layers: 4
  dropout: 0.1

small_denoiser: &small_denoiser
  <<: *default_denoiser      
  class_embed_dim: 8
  time_embed_dim: 16 
  d_model: 32             
  num_heads: 4             
  num_layers: 2
  dropout: 0.            

big_denoiser: &big_denoiser
  <<: *default_denoiser
  class_embed_dim: 128
  time_embed_dim: 256
  d_model: 256
  num_heads: 8
  num_layers: 6
  dropout: 0.2

#---------------------------------------------------------
# Training
#---------------------------------------------------------
default_train: &default_train
  lr: 0.001
  batch_size: 64
  num_epochs: 100
  loss: 'Noise'

#---------------------------------------------------------
# WandB
#---------------------------------------------------------
default_wandb: &default_wandb
  enabled: true
  project: 'penrose-diffusion'
  run_name: null        # Auto-generated if null
  run_id: null          # Specify to resume a specific run
  watch_freq: 100       # Frequency to log gradients and parameters

verbose_wandb:
  <<: *default_wandb
  enabled: true
  project: 'penrose-debug'
  watch_freq: 10

no_wandb:
  <<: *default_wandb
  enabled: false

nowatch_wandb:
  <<: *default_wandb
  enabled: true
  watch_freq: 0     

# ---------------------------------------------------------
# EXPERIMENT GROUPS
# This is what you select via CLI (e.g., -g small)
# ---------------------------------------------------------
default:
  denoiser:
    <<: *default_denoiser
  train:
    <<: *default_train
  wandb:
    <<: *default_wandb

toy:
  denoiser:
    <<: *small_denoiser
  train:
    <<: *default_train
    num_epochs: 2
  wandb:
    <<: *default_wandb
    enabled: true
    project: 'penrose-toy'
    watch_freq: 0

    
# SMALL
small:
  denoiser:
    <<: *small_denoiser
  train:
    <<: *default_train    
    lr: 0.001   
    batch_size: 64
    num_epochs: 10           
  wandb:
    <<: *default_wandb

# LARGE
large:
  denoiser:
    <<: *big_denoiser
  train:
    <<: *default_train
  wandb:
    <<: *default_wandb

