# configs.yaml

# ---------------------------------------------------------
# denoisers
# ---------------------------------------------------------
denoiser32: &denoiser32
  num_classes: 70
  class_embed_dim: 8
  time_embed_dim: 16
  d_model: 32
  num_heads: 4
  num_layers: 2
  dropout: 0.

denoiser64: &denoiser64
  num_classes: 70
  class_embed_dim: 16
  time_embed_dim: 32
  d_model: 64
  num_heads: 4
  num_layers: 4
  dropout: 0.1

denoiser128: &denoiser128
  num_classes: 70
  class_embed_dim: 32
  time_embed_dim: 64
  d_model: 128
  num_heads: 8
  num_layers: 4
  dropout: 0.1

denoiser256: &denoiser256
  num_classes: 70
  class_embed_dim: 64
  time_embed_dim: 128
  d_model: 256
  num_heads: 8
  num_layers: 6
  dropout: 0.2

#---------------------------------------------------------
# Training
#---------------------------------------------------------
default_train: &default_train
  lr: 0.001
  batch_size: 64
  num_epochs: 100
  loss: 'Noise'
  save_samples: true

#---------------------------------------------------------
# WandB
#---------------------------------------------------------
default_wandb: &default_wandb
  enabled: true
  project: 'penrose-train'
  run_name: null        # Auto-generated if null
  run_id: null          # Specify to resume a specific run
  watch_freq: 100       # Frequency to log gradients and parameters

verbose_wandb:
  <<: *default_wandb
  enabled: true
  project: 'penrose-debug'
  watch_freq: 10

no_wandb:
  <<: *default_wandb
  enabled: false

nowatch_wandb:
  <<: *default_wandb
  enabled: true
  watch_freq: 0

# ----------------------------------------------------------------
# EXPERIMENT GROUPS
# This is what you select via CLI (e.g., train.py data.npz toy)
# ----------------------------------------------------------------
default:
  denoiser:
    <<: *denoiser64
  train:
    <<: *default_train
  wandb:
    <<: *default_wandb

toy:
  denoiser:
    <<: *denoiser32
  train:
    <<: *default_train
    num_epochs: 3
  wandb:
    <<: *default_wandb
    enabled: true
    project: 'penrose-toy'
    watch_freq: 0

model32:
  denoiser:
    <<: *denoiser32
  train:
    <<: *default_train
  wandb:
    <<: *default_wandb

model64:
  denoiser:
    <<: *denoiser64
  train:
    <<: *default_train
  wandb:
    <<: *default_wandb

model128:
  denoiser:
    <<: *denoiser128
  train:
    <<: *default_train
  wandb:
    <<: *default_wandb

model256:
  denoiser:
    <<: *denoiser256
  train:
    <<: *default_train
  wandb:
    <<: *default_wandb
