toy:
  train:
    num_epochs: 3
    save_samples: false
    save_interval: 1
  wandb:
    enable: false
    project: 'penrose-toy'

#----------
# batch size
#----------
bs16:
  train:
    batch_size: 16

bs32:
  train:
    batch_size: 32

bs64:
  train:
    batch_size: 64

bs128:
  train:
    batch_size: 128

bs256:
  train:
    batch_size: 256

bs1400:
  train:
    batch_size: 1400
#----------
# Epochs
#----------
ne1:
  train:
    num_epochs: 1
    save_interval: 1

ne3:
  train:
    num_epochs: 3
    save_interval: 1

ne9:
  train:
    num_epochs: 9
    save_interval: 1

ne10:
  train:
    num_epochs: 10
    save_interval: 1

ne99:
  train:
    num_epochs: 99
    save_interval: 10

ne100:
  train:
    num_epochs: 100
    save_interval: 10

ne200:
  train:
    num_epochs: 200
    save_interval: 10
    
ne300:
  train:
    num_epochs: 300
    save_interval: 10

ne333:
  train:
    num_epochs: 333
    save_interval: 10

ne999:
  train:
    num_epochs: 999
    save_interval: 10

#----------
# WandB
#----------
w0:
  wandb:
    enable: false

w1:
  wandb:
    enable: true

#----------
# save interval
#----------
si1:
  train:
    save_interval: 1

si5:  
  train:
    save_interval: 5

si10:
  train:
    save_interval: 10

si50:  
  train:
    save_interval: 50

si100:
  train:
    save_interval: 100

#----------
# Samples
#----------
s0:
  train:
    save_samples: false

s1:
  train:
    save_samples: true

#----------
# Losses
#----------
shl:
  model:
    loss: "shl"

pil:
  model:
    loss: "pil"

cfl:
  model:
    loss: "cfl"

lpl:
  model:
    loss: "lpl"

lsa:
  model:
    loss: "lpl"

#----------
# Diffusers
#----------
ddpm:
  model:
    diffuser: "ddpm"

flow:
  model:
    diffuser: "flow"

otfm:
  model:
    diffuser: "otfm"
    loss: "npl"
    io_dim: 3
    representation: "scaled_xya"
    time_schedule: "linear"
    ot_async_prefetch: true
    ot_workers: 8
    ot_seed: null